site_name: DemaTrading.ai
nav:
    - Documentation: documentation.md
    - How it works: Hitw.md
    - Changelog: changelog.md
theme:
    name: material
    logo: assets/logo.png
repo_url: https://github.com/dema-trading-ai/engine
extra_css:
    - css/extra.css