site_name: DemaTrading.ai
nav:
    - Documentation: documentation.md
    - Changelog: changelog.md
theme: material
    icon:
      repo: fontawesome/brands/git-alt
repo_url: https://github.com/dema-trading-ai/engine
