# Triggers the Github Workflow to increase the version numher and publish an update to the Github Package.

name: Github Packages Deployment

on:
  push:
    branches:
    - release/stable

jobs:
  generate-new-tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}  # Allows publish-package to use the new_tag output.
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch  # If no triggers are found in commit messages, defaults to bumping the last digit (0.0.0 -> 0.0.1). See https://github.com/marketplace/actions/github-tag#bumping for mroe info.
          dry-run: false  # For testing purposes. Should be set to false by default.
  publish_package:
    runs-on: ubuntu-latest
    needs: generate-new-tag
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dema-trading-ai/engine:stable, dema-trading-ai/engine:${{ needs.generate-new-tag.outputs.new_tag }}  # Builds a package with the `stable` tag, and another with the version as tag.
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
