name: Docker build pipeline
on:
  push:
    branches: [main, feature]
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: VaultVulp/gp-docker-action@1.1.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        image-name: dema-engine
        image-tag: test
