name: Unit Test for Pull Requests

on:
    pull_request:
        branches: [main, development]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Run the tests
<<<<<<< HEAD:.github/workflows/test.yml
              run: echo Hello, world!
=======
              run: echo Hello, world!
>>>>>>> b8c429d1413f721ecb6d17c8131e7f559900096f:.github/workflows/unit_test_PR.yml
