name: Unit Test for Pull Requests

on:
    pull_request:
        branches: [main, development, fix/pipeline-update]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Run the tests
              run: echo Hello, world!
